# Generated by Django 6.0.2 on 2026-05-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_signeddocumentartifact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='documentrecord',
            name='owner',
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='documentrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
